# Getting started with Starling (ST)


In [21]:
# %pip install biostarling
# %pip install lightning_lite

import anndata as ad
import pandas as pd
import torch
from starling import starling, utility
from lightning_lite import seed_everything
import pytorch_lightning as pl
import numpy as np
from torch.utils.data import DataLoader


## Setting seed for everything


In [ ]:
seed_everything(10, workers=True)

INFO:lightning_lite.utilities.seed:Global seed set to 10


10

## Loading annData objects


In [42]:
anndata_train = ad.read_h5ad("train_adata.h5ad")
anndata_train.X = np.arcsinh(anndata_train.layers['exprs'] / 5.0)

anndata_train.obs["cell_cat_labels"] = anndata_train.obs["cell_labels"].astype('category').cat.codes.values
labels_map = anndata_train.obs.set_index('cell_cat_labels')['cell_labels'].to_dict()

labels = anndata_train.obs["cell_cat_labels"]

adata = utility.init_clustering("User", anndata_train, labels=labels)


- The input anndata object should contain a cell-by-protein matrix of segmented single-cell expression profiles in the `.X` position. Optionally, cell size information can also be provided as a column of the `.obs` DataFrame. In this case `model_cell_size` should be set to `True` and the column specified in the `cell_size_col_name`argument.
- Users might want to arcsinh protein expressions in \*.h5ad (for example, `sample_input.h5ad`).
- The `utility.py` provides an easy setup of GMM, KM (Kmeans) or PG (PhenoGraph).
- Default settings are applied to each method.
- k can be omitted when PG is used.


## Setting initializations


The example below uses defualt parameter settings based on benchmarking results (more details in manuscript).


In [43]:
st = starling.ST(adata)

/usr/local/lib/python3.10/dist-packages/starling/starling.py:78: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  torch.tensor(self.adata.obs[self.cell_size_col_name])


A list of parameters are shown:

- adata: annDATA object of the sample
- dist_option (default: 'T'): T for Student-T (df=2) and N for Normal (Gaussian)
- singlet_prop (default: 0.6): the proportion of anticipated segmentation error free cells
- model_cell_size (default: 'Y'): Y for incoporating cell size in the model and N otherwise
- cell_size_col_name (default: 'area'): area is the column name in anndata.obs dataframe
- model_zplane_overlap (default: 'Y'): Y for modeling z-plane overlap when cell size is modelled and N otherwise
  Note: if the user sets model_cell_size = 'N', then model_zplane_overlap is ignored
- model_regularizer (default: 1): Regularizier term impose on synthetic doublet loss (BCE)
- learning_rate (default: 1e-3): The learning rate of ADAM optimizer for STARLING

Equivalent to the above example:
```python
st = starling.ST(adata, 'T', 'Y', 'area', 'Y', 1, 1e-3)
```


## Setting training log


Once training starts, a new directory 'log' will be created.

In [44]:
## log training results via tensorboard
log_tb = pl.loggers.TensorBoardLogger(save_dir="log")

One could view the training information via tensorboard. Please refer to torch lightning (https://lightning.ai/docs/pytorch/stable/api_references.html#profiler) for other possible loggers.


## Setting early stopping criterion


In [45]:
## set early stopping criterion
cb_early_stopping = pl.callbacks.EarlyStopping(monitor="train_loss", mode="min", verbose=False)

Training loss is monitored.


## Training Starling


In [46]:
## train ST
st.train_and_fit(
    callbacks=[cb_early_stopping],
    logger=[log_tb],
)

INFO:lightning_lite.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:lightning_lite.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:lightning_lite.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name | Type | Params | Mode
-------------------------------------
-------------------------------------
0         Trainable params
0         Non-trainable params
0         Total params
0.000     Total estimated model params size (MB)
0         Modules in train mode
0         Modules in eval mode
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:617: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoa

Training: |          | 0/? [00:00<?, ?it/s]

## Appending STARLING results to the annData object


In [47]:
## retrive starling results
result = st.result()

## The following information can be retrived from the annData object:

- st.adata.varm['init_exp_centroids'] -- initial expression cluster centroids (P x C matrix)
- st.adata.varm['st_exp_centroids'] -- ST expression cluster centroids (P x C matrix)
- st.adata.uns['init_cell_size_centroids'] -- initial cell size centroids if STARLING models cell size
- st.adata.uns['st_cell_size_centroids'] -- initial & ST cell size centroids if ST models cell size
- st.adata.obsm['assignment_prob_matrix'] -- cell assignment probability (N x C maxtrix)
- st.adata.obsm['gamma_prob_matrix'] -- gamma probabilitiy of two cells (N x C x C maxtrix)
- st.adata.obs['doublet'] -- doublet indicator
- st.adata.obs['doublet_prob'] -- doublet probabilities
- st.adata.obs['init_label'] -- initial assignments
- st.adata.obs['st_label'] -- ST assignments
- st.adata.obs['max_assign_prob'] -- ST max probabilites of assignments

_N: # of cells; C: # of clusters; P: # of proteins_


## Saving the model


In [48]:
## st object can be saved
torch.save(st, "model.pt")

model.pt will be saved in the same directory as this notebook.


## Showing STARLING results


In [49]:
display(result)

AnnData object with n_obs × n_vars = 253433 × 40
    obs: 'image', 'sample_id', 'ObjectNumber', 'Pos_X', 'Pos_Y', 'area', 'major_axis_length', 'minor_axis_length', 'eccentricity', 'width_px', 'height_px', 'acquisition_id', 'SlideId', 'Study', 'Box.Description', 'Position', 'SampleId', 'Indication', 'BatchId', 'SubBatchId', 'ROI', 'ROIonSlide', 'includeImage', 'flag_no_cells', 'flag_no_ROI', 'flag_total_area', 'flag_percent_covered', 'small_cell', 'celltypes', 'flag_tumor', 'PD1_pos', 'Ki67_pos', 'cleavedPARP_pos', 'GrzB_pos', 'tumor_patches', 'distToCells', 'CD20_patches', 'Batch', 'cell_labels', 'classifier', 'cell_cat_labels', 'init_label', 'st_label', 'doublet_prob', 'doublet', 'max_assign_prob'
    var: 'channel', 'use_channel', 'marker'
    uns: 'init_cell_size_centroids', 'init_cell_size_variances', 'st_cell_size_centroids'
    obsm: 'assignment_prob_matrix', 'gamma_assignment_prob_matrix'
    varm: 'init_exp_centroids', 'init_exp_variances', 'st_exp_centroids'
    layers: 'exprs

One could easily perform further analysis such as co-occurance, enrichment analysis and etc.


In [50]:
result.obs

image  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
...                                                                                               ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713      IMMUcan_Batch20220908_S-220729-00002_002.tiff   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715      IMMUcan_Batch20220908_S-220729-00002_002.tiff   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721      IMMUcan_Batch20220908_S-220729-00002_002.tiff   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722      IMMUcan_Batch20220908_S-220729-00002_002.tiff   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725      IMMUcan_Batch20220908_S-220729-00002_002.tiff   

                                                                                            sample_id  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
...                                                                                               ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713           IMMUcan_Batch20220908_S-220729-00002_002   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715           IMMUcan_Batch20220908_S-220729-00002_002   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721           IMMUcan_Batch20220908_S-220729-00002_002   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722           IMMUcan_Batch20220908_S-220729-00002_002   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725           IMMUcan_Batch20220908_S-220729-00002_002   

                                                    ObjectNumber       Pos_X  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...             1  300.846154   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...             3   26.982143   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...             5  309.083333   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...             7  431.916667   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...             8  116.931034   
...                                                          ...         ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713          2713  596.548387   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715          2715  180.300000   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721          2721   48.370370   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722          2722  207.969697   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725          2725  565.937500   

                                                         Pos_Y  area  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    0.692308    13   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    0.928571    56   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    0.750000    12   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    0.750000    12   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    1.206897    29   
...                                                        ...   ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713  596.709677    31   
IMMUcan_Batch20220908_S-220729-00002_

Starling provides doublet probabilities and cell assignment if it were a singlet for each cell.


## Showing initial expression centroids:


In [51]:
## initial expression centroids (p x c) matrix
pd.DataFrame(result.varm["init_exp_centroids"], index=result.var_names)

0         1         2         3         4         5         6   \
0   0.042330  0.055440  0.045429  0.046147  0.058866  0.048206  0.053753   
1   0.510187  0.557392  0.512964  0.525483  0.528893  0.484494  0.471054   
2   0.086614  0.086694  0.125974  0.105891  0.138406  0.134960  0.111773   
3   0.153765  0.183137  0.234594  0.269289  0.306868  0.194293  0.369733   
4   0.115890  0.193104  0.127355  0.141434  0.108857  0.073516  0.082383   
5   0.623071  0.665065  0.532681  0.561389  0.720928  0.635850  0.678736   
6   0.228295  0.390863  0.236320  0.264384  0.177816  0.119897  0.139272   
7   0.182313  0.203169  0.193568  0.208944  0.233916  0.184893  0.201099   
8   0.465929  0.489237  0.154292  0.168922  0.153395  0.101692  0.105535   
9   0.175452  0.216623  0.213170  0.217946  0.149752  0.119206  0.450712   
10  0.455446  0.574848  0.461138  0.486587  0.465743  0.384558  0.420441   
11  0.580496  0.604134  0.151139  0.151209  0.167791  0.093654  0.101991   
12  0.267425  0.312663  0.325960  0.341951  0.387776  0.326592  0.503404   
13  0.188840  0.236075  0.234095  0.244836  0.250572  0.219623  0.213171   
14  0.199104  0.547367  0.449599  0.479224  0.195381  0.127674  0.143312   
15  0.062733  0.111552  0.084952  0.120883  0.077827  0.052874  0.061425   
16  0.221576  0.327117  0.310707  0.319696  0.501831  0.231763  0.395070   
17  0.096276  0.217587  0.158133  0.182283  0.115825  0.081224  0.097624   
18  0.214825  0.242408  0.256366  0.230236  0.258004  0.230743  0.247206   
19  0.192727  0.470900  0.349071  0.421269  0.209819  0.157480  0.183168   
20  0.225399  0.313260  0.269683  0.375530  0.260389  0.204060  0.226253   
21  0.133704  0.209745  0.174897  0.194650  0.208072  0.142464  0.179543   
22  0.195125  0.383426  0.259766  0.236948  0.188996  0.144685  0.168146   
23  0.441995  0.659055  0.600746  0.617435  0.527234  0.419397  0.496528   
24  0.098261  0.196991  0.121345  0.116577  0.120018  0.091392  0.093587   
25  0.137646  0.288395  0.224886  0.214262  0.161030  0.106829  0.123617   
26  0.196036  0.485251  0.178079  0.646368  0.199193  0.137406  0.146484   
27  0.171482  0.219019  0.232451  0.285146  0.277979  0.296781  0.275902   
28  0.286114  0.322711  0.323745  0.340253  0.361710  0.283323  0.394131   
29  0.115284  0.192128  0.164163  0.203410  0.186585  0.116189  0.120446   
30  0.186996  0.315779  0.248589  0.255749  0.240521  0.177740  0.226322   
31  0.348750  0.428936  0.262798  0.290072  0.345086  0.220184  0.289168   
32  0.301273  0.518260  0.494951  0.377089  0.399827  0.273268  0.394343   
33  0.468188  0.510996  0.538157  0.552494  0.564133  0.489279  0.664973   
34  0.264067  0.305269  0.328332  0.348117  0.404981  0.311508  0.308627   
35  0.198820  0.252581  0.221425  0.220026  0.209861  0.163235  0.195916   
36  0.189087  0.211546  0.220322  0.203424  0.200642  0.158313  0.337136   
37  0.029253  0.038049  0.039457  0.037478  0.043796  0.029527  0.040205   
38  0.816546  0.856243  0.820395  0.823125  0.775789  0.761461  0.761461   
39  0.897844  0.934935  0.901016  0.903625  0.858294  0.845048  0.845079   

          7         8         9         10        11        12        13  
0   0.039186  0.043877  0.340778  0.047716  0.042953  0.058844  0.048891  
1   0.457013  0.517266  0.557300  0.570200  0.524787  0.565808  0.547751  
2   0.246040  0.115593  0.098263  0.145649  0.051658  0.107666  0.119670  
3   0.099399  0.308056  0.150043  0.283433  0.119749  0.260154  0.211020  
4   0.058896  0.148396  0.093526  0.145153  0.086915  0.215936  0.417757  
5   0.202119  0.502270  0.343132  0.580249  0.306554  0.651017  0.393635  
6   0.106115  0.191471  0.164392  0.339419  0.132390  0.294915  0.351005  
7   0.129752  0.187617  0.865790  0.205089  0.278693  0.202749  0.166756  
8   0.078221  0.309170  0.133894  0.150798  0.129597  0.377480  0.293534  
9   0.074606  0.221459  0.140539  0.232865  0.066675  0.260143  0.185867  
10  0.293213  0.443951  0.391511  0.520850  0.368403  0.532311  0.46

There are 10 centroids since we set Kmeans (KM) as k = 10 earlier.


## Showing Starling expression centroids:


In [52]:
## starling expression centroids (p x c) matrix
pd.DataFrame(result.varm["st_exp_centroids"], index=result.var_names)

0         1         2         3         4         5         6   \
0   0.033313  0.062858  0.030869  0.042249  0.034201  0.033854  0.038436   
1   0.473998  0.695459  0.489029  0.533541  0.441941  0.422818  0.430709   
2   0.045429  0.095318  0.051425  0.085316  0.011567  0.002372  0.050554   
3   0.092179  0.465458  0.132610  0.421557  0.070000  0.029684  0.306600   
4   0.102963  0.309066  0.046091  0.113315  0.059454  0.028158  0.044092   
5   0.625823  0.737519  0.491742  0.700881  0.324188  0.110551  0.633401   
6   0.334502  0.426569  0.203024  0.196835  0.103193  0.052839  0.102079   
7   0.098183  0.156252  0.077397  0.174051  0.354846  0.508907  0.088655   
8   0.391924  0.294140  0.071940  0.136815  0.096121  0.046072  0.063869   
9   0.071937  0.323524  0.083224  0.405180  0.036090  0.016168  0.327825   
10  0.509367  0.677198  0.396979  0.514890  0.407014  0.267203  0.385291   
11  0.399950  0.238512  0.084094  0.146674  0.140364  0.062975  0.062865   
12  0.261325  0.444534  0.229270  0.492409  0.221925  0.146247  0.411931   
13  0.201405  0.347682  0.145231  0.241565  0.244324  0.130723  0.141216   
14  0.510542  0.558325  0.455739  0.229837  0.137999  0.061355  0.097323   
15  0.071116  0.200213  0.054870  0.081817  0.060640  0.029521  0.038901   
16  0.301326  0.478187  0.194836  0.426233  0.125982  0.055458  0.329623   
17  0.160424  0.242838  0.114076  0.123170  0.103754  0.058557  0.073638   
18  0.227173  0.302005  0.175972  0.261922  0.095293  0.048866  0.177258   
19  0.477669  0.495655  0.379289  0.270234  0.204487  0.060703  0.129326   
20  0.254190  0.459472  0.226584  0.307601  0.287207  0.150667  0.170581   
21  0.159787  0.336603  0.096196  0.215774  0.144281  0.071951  0.124025   
22  0.340633  0.369377  0.136440  0.222458  0.208090  0.204347  0.091229   
23  0.627293  0.685516  0.605904  0.569818  0.307384  0.307345  0.460118   
24  0.118645  0.248933  0.064009  0.131110  0.133697  0.058183  0.065011   
25  0.222107  0.387509  0.135931  0.186777  0.176823  0.067348  0.083441   
26  0.419772  0.558839  0.515378  0.173658  0.099098  0.047749  0.072611   
27  0.170476  0.314202  0.145827  0.252082  0.295688  0.195700  0.185661   
28  0.303580  0.459392  0.230315  0.454710  0.353632  0.230378  0.349578   
29  0.071775  0.246505  0.040646  0.092397  0.134909  0.359915  0.040976   
30  0.287100  0.403924  0.160234  0.292003  0.139095  0.053094  0.179456   
31  0.377860  0.496524  0.152657  0.364684  0.134984  0.027010  0.254708   
32  0.511093  0.529678  0.370665  0.447845  0.277823  0.123387  0.331544   
33  0.473319  0.672099  0.463571  0.683129  0.410608  0.192470  0.620808   
34  0.269188  0.456153  0.189664  0.384710  0.717655  0.689084  0.251128   
35  0.211106  0.345031  0.155757  0.245499  0.183183  0.047279  0.147383   
36  0.108605  0.263891  0.095225  0.317000  0.099633  0.041781  0.233526   
37  0.027785  0.054638  0.017753  0.039842  0.032827  0.016965  0.020472   
38  0.815709  0.909490  0.826483  0.818329  0.752285  0.717000  0.736005   
39  0.896468  0.985189  0.907311  0.899361  0.838051  0.801423  0.821060   

          7         8         9         10        11        12        13  
0   0.028671  0.031393  0.063674  0.049872  0.025501  0.079325  0.035480  
1   0.404287  0.389905  0.580307  0.606788  0.410119  0.793630  0.641596  
2   0.171382  0.026072  0.122430  0.032405  0.020544  0.022494  0.057160  
3   0.031200  0.050573  0.080478  0.130023  0.044790  0.301653  0.063504  
4   0.025218  0.024438  0.091397  0.127092  0.046725  0.255513  0.077255  
5   0.127320  0.287963  0.268456  0.343097  0.085095  0.392052  0.156132  
6   0.064547  0.061390  0.176711  0.194330  0.070616  0.312744  0.136463  
7   0.032982  0.316111  0.391211  0.179309  0.160617  0.158292  0.045259  
8   0.045791  0.044891  0.129727  0.185355  0.084150  0.290560  0.139972  
9   0.023537  0.024040  0.064337  0.059889  0.023854  0.092375  0.035058  
10  0.203967  0.283699  0.383240  0.504619  0.229149  0.574883  0.32

From here one could easily annotate cluster centroids to cell type.


## Showing Assignment Distributions:


In [53]:
## assignment distributions (n x c maxtrix)
pd.DataFrame(result.obsm["assignment_prob_matrix"], index=result.obs.index)

0   \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  4.819697e-15   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  1.544102e-11   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  4.182603e-11   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  1.715274e-07   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  5.715810e-11   
...                                                          ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713  4.392831e-11   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715  3.637906e-27   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721  8.411613e-07   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722  1.116901e-24   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725  2.935147e-10   

                                                              1   \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  3.036467e-27   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  2.363828e-23   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  2.774790e-10   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  2.747980e-12   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  1.158090e-17   
...                                                          ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713  5.392072e-21   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715  5.877919e-45   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721  1.236565e-14   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722  1.691231e-40   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725  3.330498e-15   

                                                              2   \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  9.863106e-07   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  1.140087e-05   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  9.355787e-09   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  7.187680e-07   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  1.166230e-04   
...                                                          ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713  4.138788e-04   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715  5.040891e-16   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721  3.796112e-02   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722  1.039714e-12   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725  4.597360e-09   

                                                              3   \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  2.114836e-09   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  4.381006e-12   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  4.523175e-01   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  2.484256e-03   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  1.223937e-06   
...                                                          ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713  1.755312e-09   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715  1.059234e-30   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721  6.039330e-03   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722  1.472362e-26   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725  9.645025e-09   

                                                              4   \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  3.622485e-15   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  6.274536e-07   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  7.572065e-19   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  8.177698e-12   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  1.012615e-05   
...                                                          ...   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713  5.770615e-13   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715  2.103454e-25   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721  7.991745e-19   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722  1.477596e-20   
IMMUcan_Batch20220908_S-220729-00002_002.tiff_

Currently, we assign a cell label based on the maximum probability among all possible clusters. However, these could be mislabeled because maximum and second highest probabilies can be very close.

## Assign labels to clusters


## Testing

In [54]:
anndata_test = ad.read_h5ad("test_adata.h5ad")
anndata_test.X = np.arcsinh(anndata_test.layers['exprs'] / 5.0)


In [55]:
def test(trained_model, test_adata, threshold: float = 0.5):
        """Test the trained model on the test data.

        :param threshold: minimum threshold for singlet probability
        """
        S = test_adata.obs['area']
        model_pred_loader = DataLoader(
            utility.ConcatDataset([test_adata.X, S]), batch_size=1000, shuffle=False
        )

        singlet_prob, singlet_assig_prob, gamma_assig_prob = utility.predict(
            model_pred_loader,
            trained_model.model_params,
            trained_model.dist_option,
            trained_model.model_cell_size,
            trained_model.model_zplane_overlap,
            threshold,
        )

        test_adata.obs["st_label"] = np.array(
            singlet_assig_prob.max(1).indices
        )  ##p(z=c|d=1)
        test_adata.obs["doublet_prob"] = 1 - np.array(singlet_prob)
        test_adata.obs["doublet"] = 0
        test_adata.obs.loc[test_adata.obs["doublet_prob"] > 0.5, "doublet"] = 1
        test_adata.obs["max_assign_prob"] = np.array(singlet_assig_prob.max(1).values)

        test_adata.obsm["assignment_prob_matrix"] = np.array(singlet_assig_prob)
        test_adata.obsm["gamma_assignment_prob_matrix"] = np.array(gamma_assig_prob)
        c = trained_model.model_params["log_mu"].detach().exp().cpu().numpy()

        test_adata.varm[
            "st_exp_centroids"
        ] = c.T  # pd.DataFrame(c, columns=test_adata.var_names)

        if test_st.model_cell_size:
            test_adata.uns["st_cell_size_centroids"] = (
                trained_model.model_params["log_psi"]
                .reshape(-1, 1)
                .detach()
                .exp()
                .cpu()
                .numpy()
                .T
            )


        return test_adata

In [56]:
test_result = test(st, anndata_test)

/usr/local/lib/python3.10/dist-packages/starling/utility.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return tuple(d[i] for d in self.datasets)


In [60]:
test_df = pd.DataFrame(test_result.obsm["assignment_prob_matrix"], index=test_result.obs.index)

In [61]:
test_df

0   \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     7.180056e-15   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     1.191193e-24   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     2.645107e-14   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     3.943732e-17   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     6.978014e-18   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  4.922848e-24   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  6.623137e-20   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  2.647938e-14   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  3.071770e-11   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2400  8.271130e-14   

                                                              1   \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     6.544796e-22   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     1.312913e-37   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     2.079836e-28   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     5.155740e-30   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     2.260007e-33   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  1.035299e-39   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  1.454933e-32   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  2.113130e-27   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  9.034238e-18   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2400  6.869121e-25   

                                                              2   \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     2.035737e-05   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     4.580353e-15   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     2.797927e-05   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     1.501028e-07   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     5.119142e-09   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  1.637690e-13   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  1.661276e-11   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  2.796058e-08   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  1.472902e-08   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2400  1.133042e-06   

                                                              3   \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     9.803418e-10   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     2.440680e-25   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     1.866736e-14   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     7.565844e-18   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     7.696814e-20   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  1.882400e-24   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  2.475183e-20   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  1.132004e-12   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  6.644621e-04   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2400  8.334907e-13   

                                                              4   \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     2.025146e-13   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     1.297680e-13   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     6.773539e-07   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     1.732028e-08   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     2.314663e-09   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  2.661686e-10   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  1.732221e-08   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  3.128148e-02   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  1.386480e-09   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_

In [63]:
test_df['predicted_label'] = np.argmax(test_result.obsm["assignment_prob_matrix"], axis=1)
test_df['predicted_label'] = test_df['predicted_label'].map(labels_map)
test_df['true_label'] = test_result.obs['cell_labels']
test_df

0  \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     7.180056e-15   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     1.191193e-24   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     2.645107e-14   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     3.943732e-17   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     6.978014e-18   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  4.922848e-24   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  6.623137e-20   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  2.647938e-14   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  3.071770e-11   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2400  8.271130e-14   

                                                               1  \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     6.544796e-22   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     1.312913e-37   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     2.079836e-28   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     5.155740e-30   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     2.260007e-33   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  1.035299e-39   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  1.454933e-32   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  2.113130e-27   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  9.034238e-18   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2400  6.869121e-25   

                                                               2  \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     2.035737e-05   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     4.580353e-15   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     2.797927e-05   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     1.501028e-07   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     5.119142e-09   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  1.637690e-13   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  1.661276e-11   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  2.796058e-08   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  1.472902e-08   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2400  1.133042e-06   

                                                               3  \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     9.803418e-10   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     2.440680e-25   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     1.866736e-14   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     7.565844e-18   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     7.696814e-20   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  1.882400e-24   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  2.475183e-20   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  1.132004e-12   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  6.644621e-04   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2400  8.334907e-13   

                                                               4  \
IMMUcan_Batch20191023_S-190805-00002_006.tiff_1     2.025146e-13   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_2     1.297680e-13   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_3     6.773539e-07   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_4     1.732028e-08   
IMMUcan_Batch20191023_S-190805-00002_006.tiff_5     2.314663e-09   
...                                                          ...   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2396  2.661686e-10   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2397  1.732221e-08   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2398  3.128148e-02   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2399  1.386480e-09   
IMMUcan_Batch20220908_S-220715-00002_002.tiff_2

In [64]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(test_df['true_label'], test_df['predicted_label']))
print(classification_report(test_df['true_label'], test_df['predicted_label']))

[[1137   18  289  225  186    4  435  209   60  174   10   16    2    2]
 [2833  133  308   47    1    0    8    2    4    2    1    0    2    0]
 [1320  262 2299 1156   47    5  396  306   89   65  113    5   15   61]
 [1395  967 2864 1157   68    9   72  113   47   18  121   17   15   27]
 [ 422   88   55  515   26    0  730   46   48   60   44    0    2   12]
 [  13    7   50  210   76   18  632  251  136  184   25   17    2    6]
 [   0  100   10 3210   23    0 3030   46    8   33   18    1    3    0]
 [   3    2   64  223   85    6  439 4659  190 2899  146  145   15  101]
 [  25   13  117  121   16    0   48   54   15   58   23    5    0    3]
 [   3   67    7  684   41   53   75   55  105 1376  132   20   13    2]
 [ 503  287  698  323    2    1   20   30    1    5   21    0    9    3]
 [  11  158  225  877 7457 6582 1001  664 5101 1106 6588 5239 1048 5399]
 [ 158   31  100  207    4    0  120   49    2  162    9    0    1    0]
 [ 135   69   65  780   26    3  160  275    6 2142

In [65]:
test_df.to_csv('test_result.tsv', sep='\t')